### ISSUE TITLE
Can't connect with Official MC

### ISSUE THREAD

**Issue by Carlosjrlu** [elyby/accounts#12]
Made a PaperMC 1.16.5 build 470 server and applied authlib-2.0.27.5, commons-io-2.5 and commons-lang3-3.5.

Works fine with Ely.by accounts, but as soon as I try to join the server with an official MC account, the server drop a **"Failed to verify username"**.

The console says:
`
Username <user> tried to join with an invalid session
`

**Comment by Nik-mmzd** [comment]
Works as intended.

**Comment by Metroite** [comment]
I am having the same issue. Ely.by accounts work, original accounts don't.

**Comment by Metroite** [comment]
@Carlosjrlu did you resolve this somehow?

**Comment by Metroite** [comment]
Oh alright. Would be a good addition.

**Comment by Metroite** [comment]
If I was to implement this feature, I would need to create an own authlib-injector web service that first tries to fetch from mojang and then, if unsuccesful, from ely.by I suppose?

**Comment by Metroite** [comment]
Implemented the feature on my fork of the [authlib-injector](https://github.com/Metroite/authlib-injector). Clone and then build with `gradlew build`.
