### ISSUE TITLE
authlib-injector support

### ISSUE THREAD

**Issue by yushijinhun** [elyby/accounts#2]
[authlib-injector](https://github.com/yushijinhun/authlib-injector) is a project that aims to provide an alternative to Mojang's authentication system, which is similar to ely.by. However, authlib-injector does not use a centralized authentication server. It provides specifications for implementing authentication APIs, and encourages people to create and deploy their own authentication servers. ([some detailed description of this project](https://github.com/bs-community/yggdrasil-api/issues/12))

I'm wondering if you can support authlib-injector.

**Comment by Carlosjrlu** [comment]
I'd love authlib-injector support as manually installing the authlib files doesn't work on a PaperMC server.

**Comment by turikhay** [comment]
@Carlosjrlu have you tried the latest version ([1.5.25.7](https://tlaun.ch/repo/libraries/by/ely/authlib/2.0.27.5/authlib-2.0.27.5.jar))?

**Comment by yushijinhun** [comment]
@erickskrauch I deployed an authlib-injector authentication server [elyby.yushi.moe](https://elyby.yushi.moe/), which forwards requests to Ely.by.

Source code: https://github.com/yushijinhun/elyby-proxy

But there are still some problems:
1. Ely.by's textures payload is not signed, but authlib-injector requires the payload to be signed with either Mojang's key or a customized key.
    * To workaround this issue, I add a signature to the response while forwarding. However, clients using authlib-injector still can't see other players' skins unless the server is using authlib-injector too.
    * This problem can be solved if Ely.by signs its textures payload with its own key.
2. Some sensitive data (passwords, tokens, ...) goes through my service. Though I will not collect or store them, others might still feel it's insecure.
    * If you host this service, there will be no security concern.

**Comment by Carlosjrlu** [comment]
@turikhay Doesn't work with PaperMC server sadly, I get this on console.

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.papermc.paperclip.Paperclip.getMainMethod(Paperclip.java:227)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:51)```
        
Tested @yushijinhun forward server and it works on server and on client.
About the security concerns, I see ely.by server accepts login with Mojang API aswell, would my players that connect with their official accounts be on a security risk?

**Comment by Nik-mmzd** [comment]
@Carlosjrlu Can't reproduce this error. Please check you've added `commons-io 2.5` and 
`commons-lang3 3.5` libraries to server classpath. Tested with authlib 2.0.27.5, Minecraft 1.16.5, Paper build 468

**Comment by erickskrauch** [comment]
@yushijinhun, I think the moment has come and it's time to finally implement this functionality on the Ely.by :) I don't give any ETA, but I'll take care of this issue as soon as possible. Thanks for the example of implementation!

**Comment by Carlosjrlu** [comment]
@Nik-mmzd 
I got the authlib from https://ely.by/load
And based on the instructions on that page I drag and dropped the content from authlib to the patched jar from paper.
Probably that's not the way it was intended to be used, but worked fine with vanilla server jar.
Can you lead me to some documentation for the server implementation of ely.by auth server?

The ely.by proxy made by @yushijinhun works fine tho.

**Comment by erickskrauch** [comment]
> And based on the instructions on [this ](https://docs.ely.by/ru/minecraft-auth.html#id9)page I drag and dropped the content from authlib to the patched jar from paper.

/\**coughs*\*, we should translate this article into English/

**Comment by Nik-mmzd** [comment]
@Carlosjrlu for newest Paper versions (1.16.4, 1.16.5) you should:
1. download latest [authlib 2.0.27.5](https://tlaun.ch/repo/libraries/by/ely/authlib/2.0.27.5/authlib-2.0.27.5.jar) as @turikhay asked, [commons-io 2.5](https://repo1.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar) and [commons-lang3 3.5](https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar)
10. drag and drop `authlib`, `commons-io` and `commons-lang3` contents (except META-INF folder) to patched Paper jar (located in cache folder)
11. run patched Paper jar

**Comment by Carlosjrlu** [comment]
@Nik-mmzd Thank you, it worked. Where did you get that info tho? How would I know if there is a new authlib version? I don't seem to find any repo for it.

Btw something to think about is that with the authlib-injector from @yushijinhun the patch is done automatically, so it is easier when updating PaperMC. So I'm looking forward to an official support.

**Comment by Nik-mmzd** [comment]
@Carlosjrlu
> Where did you get that info tho?

I'm member of Ely.by developer team
> How would I know if there is a new authlib version?

Currently there is no official way to check authlib updates... 🤔 *We definitely need to do something about it ...*

**Comment by Carlosjrlu** [comment]
@Nik-mmzd Sorry for asking in this issue but, I need to.
Is there any security concern for the players connecting to my server through their official Minecraft accounts?
Does the information sent in the payload to the elyby auth server contains password or something?

**Comment by Nik-mmzd** [comment]
@Carlosjrlu
> Is there any security concern for the players connecting to my server through their official Minecraft accounts?  
No.
> Does the information sent in the payload to the elyby auth server contains password or something?
If non-ely player will connect any server he'll send all auth request to his auth server, not Ely one, so Ely will never receive any sensetive data like access tokens from such players.

**Comment by Carlosjrlu** [comment]
Hey, are the authentication servers currently down? Can't log on to the server.

![image](https://user-images.githubusercontent.com/20954701/108025058-c5ba7780-6ff3-11eb-9cda-74a9a8f88b66.png)

**Comment by erickskrauch** [comment]
@yushijinhun, after a long wait, this task has finally been released! You can specify the domain `ely.by` (preferred), `account.ely.by` or `authserver.ely.by` as the base domain.

**Comment by JoCat** [comment]
> Currently there is no official way to check authlib updates... 🤔 _We definitely need to do something about it ..._

It is possible to write a simple server that will monitor the update of the version list https://launchermeta.mojang.com/mc/game/version_manifest.json
And based on it, do the matching of the authlib version

**Comment by yushijinhun** [comment]
> > Currently there is no official way to check authlib updates... thinking _We definitely need to do something about it ..._
> 
> It is possible to write a simple server that will monitor the update of the version list https://launchermeta.mojang.com/mc/game/version_manifest.json / https://launchermeta.mojang.com/mc/game/version_manifest_v2.json
> And based on it, do the matching of the authlib version

I'm using GitHub Actions to monitor the version list (see [yushijinhun/minecraft-version-json-history](https://github.com/yushijinhun/minecraft-version-json-history)). But it doesn't seem to make sense any more, because 1.18 experimental snapshots are not included in the list.
