### ISSUE TITLE
Retrieving a Minecraft profile with no skin returns an empty array instead of an empty object

### ISSUE THREAD

**Issue by l1ttleO** [elyby/accounts#27]
When retrieving a Minecraft profile using `/api/minecraft/session/profile/<UUID>`, the Base64-encoded texture information will have an empty *array* in the `textures` field if the user did not set a skin on the website and there's no Mojang account to proxy a skin from. However, the Mojang implementation always returns an empty *object* and launchers that explicitly check that it's an *object* will fail to add the profile until the user has set a skin

**Comment by erickskrauch** [comment]
Deployed to production. Thanks for the report!
