### ISSUE TITLE
SSL Certificate Expired! Urgent

### ISSUE THREAD

**Issue by lemonzest79** [elyby/accounts#28]
The SSL certificate for the login server expired on Dec 17th 2022 so now it's not possible to log in via a minecraft launcher which supports ely.by login.

**Comment by erickskrauch** [comment]
Oh shit.

**Comment by lemonzest79** [comment]
I'll post the relevant issue from where I found this out (affects me also) https://github.com/fn2006/PollyMC/issues/46

**Comment by erickskrauch** [comment]
Ok, it is complicated. Since we're hosted on domain `.by`, we're under sanctions because of the Russian war against Ukraine. And it makes it quite hard to get the new SSL certificate. I'll enable the Let'sEncrypt certificate, but it'll not work with outdated Java clients, which are still a lot around the internet.

I also already contacted with domain seller in order to figure out how to deal with this situation.

**Comment by lemonzest79** [comment]
Thanks

**Comment by erickskrauch** [comment]
Ok, the Let'sEncrypt certificate is now enabled for the `authserver.ely.by` domain. It should work for modern Java clients. At this point, there is nothing else I can do. I'm waiting to hear from the seller of the domain, whether they can help me buy an SSL certificate if anyone else sells them for `.by` domains.

**Comment by lemonzest79** [comment]
Can confirm now that the accounts page of PollyMC now says "Ready" for the account status and I can also log into my own server that uses ely.by auth, thanks for your help and hope everything works out for you getting the new certificate :)

**Comment by thewackymoon** [comment]
> Can confirm now that the accounts page of PollyMC now says "Ready" for the account status and I can also log into my own server that uses ely.by auth,

Can also confirm, Ely.by auth in PollyMC works now
Good luck with getting new certificates, thank you very much!

**Comment by fn2006** [comment]
Thanks, hopefully they can help you get another cert without too much hassle.

**Comment by erickskrauch** [comment]
I managed to get a certificate from GlobalSign. Now it is installed on the domain `authserver.ely.by` and even legacy versions of Java will work correctly with the service. Thank you all for your participation, this journey is over :)
